#!/bin/bash -eux

source ./common.sh
source ../common/clone-llvm.sh
# LLVM is bootstrapped so that it is all built with the same libc++ version
(
mkdir -p llvm-build-3
cd llvm-build-3
# set PATH=/opt/score-sdk/llvm/bin:$PATH

xcrun --sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk cmake -Wno-dev \
 -GNinja \
 -DCMAKE_BUILD_TYPE=Release \
 -DBUILD_SHARED_LIBS=0 \
 -DLLVM_INCLUDE_TOOLS=1 \
 -DLLVM_BUILD_TOOLS=1 \
 -DLLVM_INCLUDE_EXAMPLES=0 \
 -DLLVM_INCLUDE_TESTS=0 \
 -DLLVM_ENABLE_CXX1Z=1 \
 -DLLVM_ENABLE_LIBEDIT=0 \
 -DLLVM_ENABLE_TERMINFO=0 \
 -DLLVM_TARGETS_TO_BUILD="$LLVM_ARCH" \
 -DLLVM_ENABLE_LIBCXX=OFF \
 -DLLVM_ENABLE_LLD=OFF \
 -DLLVM_ENABLE_RTTI=ON \
 -DLLVM_ENABLE_ZLIB=ON \
 -DLLVM_ENABLE_ZSTD=OFF \
 -DLLVM_ENABLE_LIBXML2=OFF \
 -DLLVM_ENABLE_CURL=OFF \
 -DLLVM_ENABLE_HTTPLIB=OFF \
 -DLLVM_ENABLE_LIBEDIT=OFF \
 -DLLVM_ENABLE_LIBPFM=OFF \
 -DLLVM_ENABLE_CURSES=OFF \
 -DLLVM_ENABLE_FFI=OFF \
 -DLLVM_ENABLE_Z3_SOLVER=OFF \
 -DLLVM_ENABLE_LIBXAR=OFF \
 -DLLVM_ENABLE_EH=ON \
 -DLLVM_ENABLE_PROJECTS="clang;polly;compiler-rt" \
 -DCMAKE_CXX_STANDARD=20 \
 -DCMAKE_C_FLAGS="$CPUFLAGS -O3 -ffast-math -fno-finite-math-only" \
 -DCMAKE_CXX_FLAGS="$CPUFLAGS -O3 -ffast-math -fno-finite-math-only" \
 -DSANITIZER_MIN_OSX_VERSION=$MACOS_VERSION \
 -DALL_ORC_SUPPORTED_ARCH=$TARGET_ARCH \
 -DCOMPILER_RT_BUILD_ORC=ON \
 -DCOMPILER_RT_BUILD_BUILTINS=OFF \
 -DCOMPILER_RT_BUILD_SANITIZERS=OFF \
 -DCOMPILER_RT_BUILD_XRAY=OFF \
 -DCOMPILER_RT_BUILD_LIBFUZZER=OFF \
 -DCOMPILER_RT_BUILD_PROFILE=OFF \
 -DCOMPILER_RT_BUILD_MEMPROF=OFF \
 -DCOMPILER_RT_BUILD_CTX_PROFILE=OFF \
 -DCOMPILER_RT_BUILD_GWP_ASAN=OFF \
 -DCOMPILER_RT_ENABLE_IOS=OFF \
 -DCOMPILER_RT_ENABLE_WATCHOS=OFF \
 -DCOMPILER_RT_ENABLE_TVOS=OFF \
 -DDARWIN_osx_ARCHS=$TARGET_ARCH \
 -DCMAKE_OSX_SYSROOT=$MACOS_SYSROOT \
 -DCMAKE_OSX_DEPLOYMENT_TARGET=$MACOS_VERSION \
 -DCMAKE_INSTALL_PREFIX=$INSTALL_PREFIX/llvm-libs \
  $CMAKE_ADDITIONAL_FLAGS \
 ../llvm/llvm
# -DCMAKE_SHARED_LINKER_FLAGS="-L$INSTALL_PREFIX/llvm/lib -lc++ -lc++abi -Wl,-rpath,$INSTALL_PREFIX/llvm/lib" \
# -DCMAKE_EXE_LINKER_FLAGS="-L$INSTALL_PREFIX/llvm/lib -lc++ -lc++abi -Wl,-rpath,$INSTALL_PREFIX/llvm/lib" \
# -DCMAKE_MODULE_LINKER_FLAGS="-L$INSTALL_PREFIX/llvm/lib -lc++ -lc++abi -Wl,-rpath,$INSTALL_PREFIX/llvm/lib" \

xcrun cmake --build . --parallel
xcrun cmake --build . --parallel --target install/strip

)
